import './globals.css'
import type { Metadata } from 'next'
import clsx from 'clsx'
import { erode, iosevka, tasa_explorer } from './fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body
        className={clsx(
          `${tasa_explorer.variable} ${erode.variable} ${iosevka.variable}`
        )}
      >
        {children}
      </body>
    </html>
  )
}
